### ISSUE TITLE
Added environment, but no data

### ISSUE THREAD

**Issue by Doownek** [microsoft/Partner-Smart-Office#69]
We think 

this project is a great idea :)

# Steps to reproduce
We have deployed the app, and are able to login.
We have added an environment, but we can only see a line with the description of the environment.
Shouldn't we see the data/dashboard after adding the environment?

## Expected behavior
A dashboard with data

## Actual behavior
A list of added environments
![capture](https://user-images.githubusercontent.com/46785709/51324586-692eac00-1a6b-11e9-8fd2-564fb5faeb83.PNG)

**Comment by pmanaigre** [comment]
You use PowerBI to access Cosmos DB and create your desired dashboards that way. https://docs.microsoft.com/en-us/azure/cosmos-db/powerbi-visualize

**Comment by lukeapathy** [comment]
How do you know if your environment settings are correct and currently downloading data?  I am able to connect via my PowerBI and see Documents in there only.

**Comment by thomas457** [comment]
Same, I only see Documents

**Comment by ghost** [comment]
@lukeapathy thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
