### ISSUE TITLE
Not seeing Secure score data for customers with relationship = Advisor

### ISSUE THREAD

**Issue by PaulSells** [microsoft/Partner-Smart-Office#71]
We are not seeing Secure score data in the DB for a particular active customer, the only difference I can see is that the customer has 'Advisor' in the relationship status field whereas all other customers have 'Cloud Reseller' 

Is this by design? Should we be able to see data within the DB irrespective of the Relationship status?

Thanks

**Comment by ghost** [comment]
@PaulSells thank you for opening this issue. Yes, that was be design the advisor should have been filtered out. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
