### ISSUE TITLE
Alerts Cosmos partition key

### ISSUE THREAD

**Issue by despian** [microsoft/Partner-Smart-Office#73]
Hi,

I'm building a similar application for our organisation and this repo has been very useful for me as a reference. Thanks!

I was wondering if you could maybe help me out with some advice or explanation of one of your design decisions.

I can see that you chose not to partition the alerts collection in the Cosmos DB. I assume this is because you expect there to be lots of queries for all alerts regardless of the tenant. Is that correct?

I expect the majority of queries against alerts in our app to also be cross-tenant however there are likely to a fair amount of tenant-specific queries as well. Would you recommend not to use a partition key on this collection? What considerations are there other than the 10GB partition size limit and query/write performance?

I suppose using the tenant as a partition key will increase our write performance if we are making parallel calls to the APIs to update the alerts. Initially, our app will be syncing alerts from the graph and security centre APIs for around 300-400 tenants but this will likely scale up. The goal would be to sync about every 5-10 mins or so.

Sorry if this is an inappropriate channel for these questions.

Thanks,
Matt

**Comment by ghost** [comment]
@despian thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
