### ISSUE TITLE
Issue with secure score data import

### ISSUE THREAD

**Issue by andycoxuk** [microsoft/Partner-Smart-Office#75]
Hi all:- complete programming novice here; but experienced 365 and azure administrator.  I am attempting to deploy the partner secure score into our CSP environment.  Have deployed successfully and can pull data into PowerBi; but the actual securescore itself isnt pulled in:- the cosmodb securescore document is empty whereas the other fields (customer; secure score controls etc) have data in them.  Have tried browsing the cosmodb in azure and it shows know data in securescore.:- any help, guidance much apprecitated

**Comment by thomas457** [comment]
Same, everything looks to be working but my SecureScore table is empty and everything else is just Document.

**Comment by thomas457** [comment]
So I found out how to fix the document part of PowerBI 
https://docs.microsoft.com/en-us/azure/cosmos-db/powerbi-visualize 

But still no luck with the SecureScore table

**Comment by ghost** [comment]
@andycoxuk thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
