### ISSUE TITLE
Using deploy script with MFA

### ISSUE THREAD

**Issue by martinwelen** [microsoft/Partner-Smart-Office#76]
Hi,

It seems like the deployment script does not allow for MFA use.

That would be a good thing to have.

**Comment by ghost** [comment]
@martinwelen thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
