### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Trafalger1** [microsoft/Partner-Smart-Office#78]
Would it be possible to get the FAQ docs updated to match the current Azure interface, I am unable to setup the software after many hours of trying because the items the FAQ calls for do not match what's in azure or it is not intuitive on what values are needed.  I am not a software developer so I am not familiar with all of the IDs and such if they are not where the FAQ says they should be.

**Comment by ManuInNZ** [comment]
@isaiah
Probably best to have an AZ CLI/powershell script to run in cloud shell to
create the app and SP as well as a simple output with just the information
to populate in app settings etc...
If you do not have time I may have such script somewhere.

**Comment by isaiahwilliams** [comment]
Hi @Trafalger1, 

Yes, we will be updating the documentation with the upcoming update. Several new features are being added. My goal is to have the new version available by the end of this month. 

@ManuInNZ that is a great idea. There is a PowerShell in the repo that does provision everything, but I believe there are enhancements we can make to simplify the entire process. This is one of the areas that I am trying to focus on with the upcoming release. If you are interested you can see what work has been done, by examining the dev branch.

**Comment by ghost** [comment]
@Trafalger1 thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
