### ISSUE TITLE
Partitionkey for SecureStore Table seems to be wrong

### ISSUE THREAD

**Issue by g-martinse** [Microsoft/Partner-Smart-Office#83]
The partition key for SecureStore is currently "/tenantId". Shouldn't this be "/azureTenantId". The SecureStore data type does not have a property "tenantID".
In my tests this led to an exception:
Exception while executing function: ProcessSecurity Message: {"Errors":["Encountered exception while executing function. Exception = Error: {\"Errors\":[\"**Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted**.\"]}\r\nStack trace: Error: {\"Errors\":[\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\"]}\n   at callback (script.js:35:18)\n   at Anonymous function (script.js:758:29)"]}

**Comment by ghost** [comment]
@g-martinse thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
