### ISSUE TITLE
Deployment script throwing error

### ISSUE THREAD

**Issue by adnantocode** [Microsoft/Partner-Smart-Office#84]
I have node idea what I'm doing wrong but getting this error when using script

C:\scritps\Deploy-PartnerSmartOffice.ps1 : Cannot bind argument to parameter 'ObjectId' because it is null.
At line:1 char:1
+ .\Deploy-PartnerSmartOffice.ps1 -ConfigurePreconsent $true -DisplayNa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Deploy-PartnerSmartOffice.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Deploy-PartnerSmartOffice.ps1

Please help

**Comment by ghost** [comment]
@adnantocode thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
