### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by geekynickuk** [Microsoft/Partner-Smart-Office#85]
The documentation on setting this up is not very clear.

The deployment script doesn't work properly unless you pass both tenant ID's on CLI, which is not clear in the documentation.

The information required for adding a new environment isn't clear enough - I'm not sure where half of these values should come from.

After a lot of messing, it appears that this won't work for indirect resellers, as we cannot use the Partner Center API? If this is the case that should also be called out in the documentation.

**Comment by ghost** [comment]
@geekynickuk  thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
