### ISSUE TITLE
Indirect CSP

### ISSUE THREAD

**Issue by shnax1** [Microsoft/Partner-Smart-Office#86]
Hi
 I just want to confirm my readings are correct that this cannot be done as an Indirect CSP?
We are an indirect CSP and have implemented this but now struggling with Partner Center Configurations where our research suggests as an Indirect CSP we cannot use as the reference to finding the relevant details in the Cloud App Management is not a feature for Indirect CSP.
Can you pls confirm?   Any other ways out there to be able to get a single view of all tenants Security Score? Its a great value add

**Comment by ghost** [comment]
@shnax1 with the design of this solution it will not work for indirect resellers. However, I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). This new project will work with the indirect reseller channel. With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
