### ISSUE TITLE
application not working and no reports exists

### ISSUE THREAD

**Issue by yurykissin** [Microsoft/Partner-Smart-Office#87]
Hi, was able to deploy the service to my azure (all apps, cosmosdb and etc created). when azure function run, i see data in the customers table but the SecureScore table is empty. I think its because:
[Error] Executed 'ProcessSecurity' (Failed, Id=25475f4a-53dc-4e5b-960d-0031bdbe70ce)
No value for named parameter 'AppEndpoint'.

**Comment by ghost** [comment]
@yurykissin thank you for opening this issue. I am in the process of retiring this project because it is being replaced by [Security and Management Insights Connector](https://github.com/microsoft/secmgmt-insights-connector). With this in mind, I would like to encourage you to review that project and open any feature request if there are additional items you are interested in seeing.
